### ISSUE TITLE
Handling multiple push / pop operations

### ISSUE THREAD

**Issue by rm-code** [rm-code/screenmanager#9]
As discussed in #2:

What if the user wants to pop() two screens from the current screen? Imagine something like this: You have a game screen, the player opens an inventory screen and in that screen he opens an compare items screen. For the player it would be convenient to just press 'i' to close the inventory screen.

This wouldn't be possible with https://github.com/rm-code/screenmanager/commit/c27ea3d3ccbe68f8c36e07045ecf22d7de386443 if I'm not mistaken. But it's not a hard issue to fix. We could simply use a "queue" for the actions.

I'm thinking about something like this:
```lua
local changes = {};

...
function ScreenManager.switch( screen, ... )
    validateScreen( screen );
    changes[#changes + 1] = { action = 'switch', screen = screen, args = { ... } };
end
...

function ScreenManager.performChange()
    if #changes == 0 then
        return
    end

    for _, change in ipairs( changes ) do
        if change.action == 'pop' then
            pop();
        elseif change.action == 'switch' then
            clear();
            push( change.screen, change.args );
        elseif change.action == 'push' then
            push( change.screen, change.args );
        end
    end

    changes = {};
end
```

**Comment by pablomayobre** [comment]
Could you check [this changes](https://github.com/rm-code/screenmanager/compare/master...Positive07:queue-changes) and tell me what you think?

**Comment by rm-code** [comment]
> The problem with that is that if you switch and then pop we have no way to know that we popped the last state and that an error should be raised. You could pop 10 times when there are only 3 states in the stack...

The user shouldn't be able to pop / push after a switch action anyway so we could discard those after the switch has been performed.

So if we use a loop we could simply break after the switch:
```
for _, change in ipairs( changes ) do
    if change.action == 'pop' then
        pop();
    elseif change.action == 'switch' then
        clear();
        push( change.screen, change.args );
        break; -- Discard any actions after the switch.
    elseif change.action == 'push' then
        push( change.screen, change.args );
    end
end
```
IMO it's the responsibility of the coder to keep track of his screens, but as you said we could simply ignore a pop action if only one screen is on the stack.

**Comment by pablomayobre** [comment]
I think what I did fixes this issue, I have a counter that actually knows the height of the stack after `performChanges` is called. So when you call `ScreenManager:pop()` but the height is already 1 it will error, even though you haven't really performed the changes in the stack

Also note that discarding any actions after the switch is bad too, because actions could be pushes and you want to take those into account

**Comment by rm-code** [comment]
I don't think we need a second variable to keep track of the stack's height. We can use `#stack` in the pop function directly:

```lua
---
-- Close and pop the current active state and activate the one beneath it
--
local function pop()
    if #stack == 1 then
        -- Do something.
        return;
    end
    -- ... 
end
```

I'm currently just thinking about what to do in this case. As I said IMO it's the programmers job to keep track of the screens and I think if you call `pop` three times in your code, but only have two screens on the stack it might be a bug you don't want to ignore... hmm no clue.

I gotta go now though. I'll implement it in OTR later today and see how it feels.

**Comment by pablomayobre** [comment]
Well `#stack` will only hold a valid value after you call `ScreenManager.performChange()` and we want a valid value when we call `ScreenManager.pop()` so I think that having a separate variable is not that bad, it should also be more performant, since getting the length of a table is way more complicated than grabbing a number variable.

My solution gives an error when you call `ScreenManager.pop()` the second time and there were only 2 screens telling you that you can't remove the last screen in the stack.

If you don't want a second variable then we can put it into the `stack` table as `stack.height` but it would be the same...

**Comment by pablomayobre** [comment]
I don't think that the user of the library should know perfectly what the stack holds since we are not even letting him access the stack himself, (the stack is a private variable). We don't even tell the user the length of the stack, and the only access the user has is `ScreenManager.peek()`

I also consider that not erroring when you pop more than what you can will actually lead to undefined behaviour and people will find it really hard to debug.

I think my solution (which you can find [here](https://github.com/rm-code/screenmanager/compare/master...Positive07:queue-changes)) addresses all this problems, with the cost of one extra variable called `height` that could be part of one of the tables like I said before (`stack.height`).

Please check that out whenever you implement this in OTR and tell me if there is anything wrong.

**Comment by rm-code** [comment]
I merged your changes, but I think we could simply do it like this:
https://github.com/rm-code/screenmanager/commit/98ab92529598e4e9e8465a010f91fbb22fc00a09

> Well #stack will only hold a valid value after you call ScreenManager.performChange()

I'm not sure what you mean by that. If we check the `#stack` in the local pop function it will always have the correct size. Of course we can't use it in the public pop function like that :)

**Comment by pablomayobre** [comment]
I think the error should go in the public `ScreenManager.pop` function (just like what I committed), because that is the expected behaviour (at least for me).

Putting the error in the private pop and making it level 2 means that I will get an stackoverflow like this:
```
Error:
ScreenManager.lua:119: Can't close the last screen. Use switch() to clear the screen manager and add a new screen.

stack traceback:
ScreenManager.lua:112: In function ScreenManager.performChange
ScreenManager.lua:212: In function ScreenManager.draw
main.lua:20: In function love.draw
...
```

With the error in the public pop you get pointed to the line where you popped more than what you should. I think that is better.

**Comment by rm-code** [comment]
Ok that makes sense. Let's leave it like this for now.
